insert into tweets values(1,'Margot','Bonjour comment allez-vous ? #happy','#happy',now(),now()),
(2,'Margot','Programmer une passion #informatique #cool','#informatique #cool',now(),now()),
(3,'Margot','Je vais au restaurant ce soir #cool!','#cool',now(),now()),
(4,'Margot','Splitfire est très intéressant #entreprise','#entreprise',now(),now()),
(5,'Margot','Vivement le soleil #sun','#sun',now(),now()),
(6,'Margot','La température baisse #winter','#winter',now(),now()),
(7,'Theo','Je passe le permis demain #permis','#permis',now(),now()),
(8,'Theo','Je recherche une alternance #etudes','#etudes',now(),now()),
(9,'Theo','Tu es cool Thomas #cool','#cool',now(),now()),
(10,'Theo','Je me lance dans laravel/lumen #informatique','#informatique',now(),now()),
(11,'Theo','Je fais un test #test','#test',now(),now()),
(12,'Thomas','Je fais des tests #test','#test',now(),now()),
(13,'Thomas','Je fais plusieurs tests #test','#test',now(),now()),
(14,'Lucas','Je cuisine un poulet demain #manger #poulet','#manger #poulet',now(),now()),
(15,'Emma','Je prépare un gâteau à la fraise #manger #faim','#manger #faim',now(),now()),
(16,'Emma','Je suis trop drôle #lol #fun','#lol #fun',now(),now()),
(17,'Emma','Je suis un surhomme #lol #funny','#lol #funny',now(),now()),
(18,'Emma','Les crepes quel délice #crepes #happy','#crepes #happy',now(),now()),
(19,'Emma','Netflix + mon chéri = parfait #netflix #amour','#netflix #amour',now(),now()),
(20,'Emma','Je démarre mon projet #projet','#projet',now(),now()),
(21,'Emma','Maison bleu #maison','#maison',now(),now()),
(22,'Emma','Une porte est meilleure au prix #porte','#porte',now(),now()),
(23,'Emma','Oh relax #chill #happy','#chill #happy',now(),now()),
(24,'Emma','Les études... #soon #etudes','#soon #etudes',now(),now()),
(25,'Emma','Pourquoi se lancer dans ce domaine ? #informatique','#informatique',now(),now()),
(26,'Paul','Happy happy happy #happy','#happy',now(),now()),
(27,'Paul','Sad sad sad #sad','#sad',now(),now()),
(28,'Paul','Pourquoi vivre ? #pourquoi','#pourquoi',now(),now()),
(29,'Paul','Les araignées... #jecomprendspas','#jecomprendspas',now(),now()),
(30,'Margot','Ma nouvelle voiture, une audi #voiture','#voiture',now(),now()),
(31,'Margot','Le permis bientôt #permis','#permis',now(),now()),
(32,'Margot','Quelle opportunité ! #splitfire','#splitfire',now(),now()),
(33,'Margot','Je suis maman #maman','#maman',now(),now()),
(34,'Margot','Je suis papa #papa','#papa',now(),now()),
(35,'Francis','Je vous annonce que... #bebe','#bebe',now(),now()),
(36,'Francis','Une nouvelle lancée #java','#java',now(),now()),
(37,'Gaetan','Encore et encore #java','#java',now(),now()),
(38,'Léa','La nouvelle génération a un bel avenir #generation','#generation',now(),now()),
(39,'Estelle','Les années 80 #generation','#generation',now(),now()),
(40,'Estelle','Je lâche souvent des improvisations #freestyle','#freestyle',now(),now()),
(41,'Estelle','Mon nouveau sport #skate #fun','#skate #fun',now(),now()),
(42,'Dimitri','Le skate trop facile #skate #lol','#skate #lol',now(),now()),
(43,'Dimitri','Gros parcours demain #bike','#bike',now(),now()),
(44,'Dimitri','Ce nouveau rappeur ! #kanoe #freestyle','#kanoe #freestyle',now(),now()),
(45,'Dimitri','Vous aimez le rap ? #rap','#rap',now(),now()),
(46,'Dimitri','La Tour Eiffel #paris','#paris',now(),now()),
(47,'Garance','Le champ de Mars #paris','#paris',now(),now()),
(48,'Garance','Je veux voir Big Ben #londres','#londres',now(),now()),
(49,'Hubert','La plus belle ville #paris','#paris',now(),now()),
(50,'Serge','Pourquoi aller à Paris ? #paris','#paris',now(),now()),
(51,'Eva','Quel style de rap écouter ? #rap','#rap',now(),now()),
(52,'Eva','Que cuisiner ? #faim #nourriture','#faim',now(),now()),
(53,'Eva','Stop.. trop dur #ecole','#ecole',now(),now()),
(54,'Stephanie','Les serpents beurk #sale','#sale',now(),now()),
(55,'Stephanie','Mon fils en maternelle #ecole','#ecole',now(),now()),
(56,'Eliott','Il me faut de nouveaux pantalons #shopping','#shopping',now(),now()),
(57,'Eliott','Mcdo toujours aussi bon #mcdo #manger','#mcdo #manger',now(),now()),
(58,'Jamy','Ma copine veut toujours faire les boutiques #shopping','#shopping',now(),now()),
(59,'Jamy','Je passe mes journées à jouer #geek','#geek',now(),now()),
(60,'Adrien','Bien joué Nancy #foot','#foot',now(),now()),
(61,'Adrien','Ce soir foot #match #foot','#match #foot',now(),now()),
(62,'Adrien','Je rentre en école supérieure #ecole #etudes','#ecole #etudes',now(),now()),
(63,'Adrien','Le chat a griffé mon canapé !!! #animaux','#animaux',now(),now()),
(64,'Edouard','Le chien est adorable #animaux','#animaux',now(),now()),
(65,'Edouard','Vous devez y penser ! #ecologie','#ecologie',now(),now()),
(66,'Margot','Ce garçon est pas mal #pasmal','#pasmal',now(),now()),
(67,'Margot','Mon gâteau est... #parfait #lol','#parfait #lol',now(),now()),
(68,'Margot','Je suis un prince #prince #lol','#prince #lol',now(),now()),
(69,'Margot','On pose la fenêtre #travaux','#travaux',now(),now()),
(70,'Margot','Encore des travaux... #travaux','#travaux',now(),now()),
(71,'Margot','Anniversaire soon !! #anniversaire #soon','#anniversaire #soon',now(),now()),
(72,'Margot','Ma meilleure amie, tu es tout à mes yeux #meilleureamie','#meilleureamie',now(),now()),
(73,'Margot','Je fais un test en anglais #drole #test','#drole #test',now(),now()),
(74,'Margot','Je fais un test en mathématiques #funny #test','#funny #test',now(),now()),
(75,'Margot','Je fais un test en français #fun #test','#fun #test',now(),now()),
(76,'Margot','Je fais un test en c# #happy #test','#happy #test',now(),now()),
(77,'Margot','Je me lance dans le rap #rap','#rap',now(),now()),
(78,'Margot','Pourquoi une porte coûte aussi chère ? #porte #aie','#porte #aie',now(),now()),
(79,'Margot','Je vais acheter une maison #maison','#maison',now(),now()),
(80,'Margot','On veut me faire croire que la prison a de bonnes conditions de vie #prison','#prison',now(),now()),
(81,'Margot','Mon visage est... #defauts','#defauts',now(),now()),
(82,'Margot','Mon enfant rentre dans le monde du travail #aie','#aie',now(),now()),
(83,'Margot','Ma phobie, les serpents #peur','#peur',now(),now()),
(84,'Margot','Je me suis bléssé au bras #aie','#aie',now(),now()),
(85,'Margot','Mon chéri est adorable avec moi #amour #aimer','#amour #aimer',now(),now()),
(86,'Margot','Aimer ça blesse #aimer','#aimer',now(),now()),
(87,'Margot','Qui sait faire un cupcake ? #help #cuisine','#help #cuisine',now(),now()),
(88,'Margot','Quelle est votre musique préférée ? #musique','#musique',now(),now()),
(89,'Margot','Je suis une fêtarde #fete','#fete',now(),now()),
(90,'Margot','Les étoiles sont trop belles #night','#night',now(),now());